name: Build and Push Docker Image
on:
  push:
    branches:
      - release
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    # Add permissions for GitHub Container Registry
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV    
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.tag.outputs.INCLUDE_VERSION_TAG == 'true' && format('ghcr.io/{0}/demo-simple-app:latest,ghcr.io/{0}/demo-simple-app:{1}', github.repository_owner, steps.tag.outputs.TAG_NAME) || format('ghcr.io/{0}/demo-simple-app:latest', github.repository_owner) }}
